Wordpress - Move off SW root scope
OneSignal/OneSignal-WordPress-Plugin pull request #268
Opened 2021-03-23 19:27 UTC by devpato

https://app.asana.com/0/1200001281475104/1199993616956902

2021-03-23 19:55 UTC, jkasten2 requested changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-wordpress-plugin/268)* status: all files reviewed, 3 unresolved discussions (waiting on @devpato)

___
*[onesignal-public.php, line 75 at r1](https://reviewable.io/reviews/onesignal/onesignal-wordpress-plugin/268#-MWVcCQS4OpXA0peP8m1:-MWVcCQS4OpXA0peP8m2:brrmg5h) ([raw file](https://github.com/onesignal/onesignal-wordpress-plugin/blob/3e63c2c27717f305db2cdb0c0a8e4a83378c90c0/onesignal-public.php#L75)):*
> ```PHP
>              * /wp-content/plugins/onesignal-free-web-push-notifications/
>              */
>             $path = strstr(plugin_dir_url(__FILE__), '/wp-content');
> ```

nit, `$path` is only used in the if-block. If we moved it inside the if-block the scope of it would be more clear.
___
*[onesignal-public.php, line 83 at r1](https://reviewable.io/reviews/onesignal/onesignal-wordpress-plugin/268#-MWVdA_e-eND3V6KTCri:-MWVdA_e-eND3V6KTCrj:b9pjkqd) ([raw file](https://github.com/onesignal/onesignal-wordpress-plugin/blob/3e63c2c27717f305db2cdb0c0a8e4a83378c90c0/onesignal-public.php#L83)):*
> ```PHP
>                 echo 'OneSignal.SERVICE_WORKER_UPDATER_PATH = "OneSignalSDKUpdaterWorker.js.php";
>                       OneSignal.SERVICE_WORKER_PATH = "OneSignalSDKWorker.js.php";
>                       OneSignal.SERVICE_WORKER_PARAM = { scope: "push/onesignal" };';
> ```

Let's leave the scope as-is for the original. This way the only change we are introducing will be for those who setup the plugin for the first time.
___
*[onesignal-settings.php, line 90 at r1](https://reviewable.io/reviews/onesignal/onesignal-wordpress-plugin/268#-MWVddiYD8GpxV3gANBN:-MWVddiYD8GpxV3gANBO:b-1b8447) ([raw file](https://github.com/onesignal/onesignal-wordpress-plugin/blob/3e63c2c27717f305db2cdb0c0a8e4a83378c90c0/onesignal-settings.php#L90)):*
> ```PHP
>                   'show_notification_send_status_message' => true,
>                   'use_http_permission_request' => 'CALCULATE_SPECIAL_VALUE',
>                   'persist_notifications' => 'CALCULATE_SPECIAL_VALUE'
> ```

Missing a comma at the end of this line.


<!-- Sent from Reviewable.io -->

2021-03-25 21:26 UTC, jkasten2 commented
Tested this branch as totally new OneSignal Wordpress install and new `.js` ServiceWorker was installed.
![image](https://user-images.githubusercontent.com/645861/112545933-05ece280-8d76-11eb-880d-3debe62ac3bf.png)

2021-03-26 18:13 UTC, jkasten2 requested changes
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-wordpress-plugin/268)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @devpato and @jkasten2)

___
*[onesignal-settings.php, line 112 at r3](https://reviewable.io/reviews/onesignal/onesignal-wordpress-plugin/268#-MWjjF2E9-HO6PvL-HTC:-MWjjF2E9-HO6PvL-HTD:blvg7w7) ([raw file](https://github.com/onesignal/onesignal-wordpress-plugin/blob/83a6d8254a51d760e1c121b63b0c5c4c4004bfcc/onesignal-settings.php#L112)):*
> ```PHP
>     if (empty( $onesignal_wp_settings )) {
>         $is_new_user = true;
>         $defaults['onesignal_sw_js'] = true;
> ```

This line can be removed, the if we added below already covers this.


<!-- Sent from Reviewable.io -->

2021-03-26 18:25 UTC, jkasten2 approved these changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-wordpress-plugin/268)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @devpato)



<!-- Sent from Reviewable.io -->

2021-03-26 18:26 UTC, merged

2021-07-17 16:27 UTC, yogeshbeniwal commented
Deletion and reinstallation of plugin is also not updating scope to push/onesignal. This may be because of settings remained saved in database and reused on reinstallation.

In this case how will it affect PWA plugin service worker installed with scope to root? Or this is ok and accepted behaviour.