Added AMP Support
OneSignal/OneSignal-WordPress-Plugin pull request #276
Opened 2021-07-16 16:56 UTC by milindmore22

Added AMP Compatability

2021-08-11 16:48 UTC, milindmore22 commented
@rgomezp any updates on this PR? 
ampproject/amp-wp#6453

2022-02-22 22:02 UTC, rgomezp requested changes
Howdy @milindmore22 ,
Thanks for your PR and also your patience!

This PR looks great, just left a couple nits for you. Let's get this merged!

Thanks so much again.

2022-02-22 22:02 UTC, rgomezp commented on onesignal-public.php
> +		if ( function_exists( 'is_amp_endpoint' ) && is_amp_endpoint() ) {
It looks like this function [has been deprecated](https://amp-wp.org/reference/function/is_amp_endpoint/)

2022-02-22 22:02 UTC, rgomezp commented on onesignal-public.php
> +		add_action( 'wp_enqueue_scripts', array( __CLASS__, 'onesigal_amp_style' ) );
Nit: indentation

2022-02-23 11:49 UTC, milindmore22 commented on onesignal-public.php
> +		if ( function_exists( 'is_amp_endpoint' ) && is_amp_endpoint() ) {
Good catch, replaced with [amp_is_request ](https://amp-wp.org/reference/function/amp_is_request/)

2022-02-23 11:50 UTC, milindmore22 commented on onesignal-public.php
> +		add_action( 'wp_enqueue_scripts', array( __CLASS__, 'onesigal_amp_style' ) );
Updated PR code with space indentation.

2022-02-23 11:51 UTC, milindmore22 commented
@rgomezp Addressed PR feedback

2022-02-25 00:01 UTC, rgomezp approved these changes

2022-02-25 00:01 UTC, merged

2022-02-25 00:11 UTC, jkasten2 reviewed
PR looks good to me

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-wordpress-plugin/276#-:-MwiCvn38qBV0yh7A4zg:bw5yd0f)* status: all files reviewed, 2 unresolved discussions



<!-- Sent from Reviewable.io -->